const QRCode = require('qrcode');
const fs = require('fs');

// Copy your infoData array from viewer.js and paste it here:
const infoData = [
  { name: "LHC" },
{ name: "Mess & Canteen" },
{ name: "R&D Block" },
{ name: "Sports Block" },
{ name: "Old Academic Block" },
{ name: "Library" },
{ name: "Girls Hostel" },
{ name: "Old Boys Hostel" },
{ name: "H1 Hostel" },
{ name: "H2 Hostel" },
{ name: "Guest House" },
{ name: "Anuj Grover Sir" },
{ name: "LHC 101" },
{ name: "LHC 102" },
{ name: "LHC 201" },
{ name: "LHC 208" },
{ name: "LHC 209" },
{ name: "LHC 210" },
{ name: "LHC 211" },
{ name: "LHC 212" },
{ name: "LHC 213" },
{ name: "LHC 214" },
{ name: "LHC 215" },
{ name: "LHC 216" },
{ name: "LHC 301" },
{ name: "LHC 302" },
{ name: "LHC 303" },
{ name: "LHC 304" },
{ name: "LHC 305" },
{ name: "LHC 306" },
{ name: "LHC 307" },
{ name: "LHC 315" },
{ name: "LHC 316" },
{ name: "LHC 317" },
{ name: "LHC 318" },
{ name: "LHC 319" },
{ name: "LHC 320" },
{ name: "LHC 321" },
{ name: "LHC 322" },
{ name: "Kapil Chawla Sir" },
{ name: "Shishir Jain Sir" },
{ name: "Store Room" },
{ name: "Nidhi Yadav Mam" },
{ name: "Finance & Accounts" },
{ name: "Anurag Tyagi Sir" },
{ name: "Umesh Singhania Sir" },
{ name: "Visiting Psychiatrist" },
{ name: "Visiting Psychologist" },
{ name: "Counselling Psychologist" },
{ name: "Khushpinder Sharma Sir" },
{ name: "Student Affairs Office" },
{ name: "Anupam Saronwala Sir" },
{ name: "Alok Nikhil Jha Sir" },
{ name: "Nayana Samuel Sir" },
{ name: "Pankaj Vajpayee Sir" },
{ name: "Center For Quantum Technologies" },
{ name: "Sankha Suvra Bhaumik Mam" },
{ name: "Anoop Ratn Sir" },
{ name: "Aman Samuel Sir" },
{ name: "Vinish Kathuria Sir" },
{ name: "Angshu Das Sir" },
{ name: "A001" },
{ name: "A002" },
{ name: "A003" },
{ name: "A004" },
{ name: "Audio Visual" },
{ name: "A006" },
{ name: "A007" },
{ name: "A101" },
{ name: "Audio Studio" },
{ name: "Production Control Room" },
{ name: "Video Studio" },
{ name: "A106" },
{ name: "Mrinmoy Chakrabarty" },
{ name: "Praveen Priyadarshi Sir" },
{ name: "Soibam Haripriya" },
{ name: "Nishad Patnaik Sir" },
{ name: "Satish Kumar Pandey Sir" },
{ name: "Deepak Prince Sir" },
{ name: "Prahllad Deb Sir" },
{ name: "Ruhi Sonal Mam" },
{ name: "Garima Rani Mam" },
{ name: "G.P.S Raghava Sir" },
{ name: "Gaurav Ahuja Sir" },
{ name: "Vibhor Kumar Sir" },
{ name: "Ganesh Bagler Sir" },
{ name: "Debarkar Sengupta Sir" },
{ name: "Jaspreet Kaur Dhanjal Mam" },
{ name: "Sriram K. Sir" },
{ name: "Tavpritesh Sethi Sir" },
{ name: "Arjun Ray Sir" },
{ name: "N.Arul Murugan Sir" },
{ name: "Tarini Shankar Ghosh Sir" },
{ name: "Public Health Lab" },
{ name: "A320" },
{ name: "Binu Annu Joseph Sir" },
{ name: "Kalpana Shankhwar Mam" },
{ name: "Anmol Srivastava Sir" },
{ name: "Sonal Keshwani Mam" },
{ name: "Richa Gupta Mam" },
{ name: "Rajiv Ratn Shah Sir" },
{ name: "Jainendra Shukla Sir" },
{ name: "Pragma Kar Mam" },
{ name: "Midas Lab" },
{ name: "Creative Interfaces Lab" },
{ name: "Dreamrs Lab" },
{ name: "Design Studio" },
{ name: "Imran Khan Sir" },
{ name: "Piyush Bagga Sir" },
{ name: "Pushpendra Singh Sir" },
{ name: "Ravi Anand Sir" },
{ name: "Piyus Kedia Sir" },
{ name: "Dhruv Kumar Sir" },
{ name: "Mukesh Mohania Sir" },
{ name: "Vikram Goyal Sir" },
{ name: "B.N Jain Sir" },
{ name: "Gautam Shroff Sir" },
{ name: "Ojaswa Sharma Sir" },
{ name: "Tanmoy Kundu Sir" },
{ name: "Graphics Research Group" },
{ name: "Systems & Software Engineering" },
{ name: "General Computing Lab" },
{ name: "A520" },
{ name: "Sanjna Khosla Mam" },
{ name: "Tammam Tilo Sir" },
{ name: "Sayan Basu Roy Sir" },
{ name: "Pravesh Biyani Sir" },
{ name: "Abhijit Mitra Sir" },
{ name: "Debidas Kundu Sir" },
{ name: "Sujay Deb Sir" },
{ name: "Manuj Mukherjee Sir" },
{ name: "Vivek Ashok Bohara Sir" },
{ name: "Mobility & Optimisation Lab" },
{ name: "Advanced Multi-Core Systems Lab" },
{ name: "Metasurface Research Lab" },
{ name: "Centre of excellence - LiFi" },
{ name: "Optical Networks Lab" },
{ name: "Advanced Electronics & Communication Lab" },
{ name: "M.Tech Lab" },
{ name: "A618" },
{ name: "Ajay Kumar Sir" },
{ name: "Ankit Agarwal Sir" },
{ name: "IT Helpdesk" },
{ name: "Adarsh Agarwal Sir" },
{ name: "Bhawani Shah Mam" },
{ name: "Rahul Verma Sir" },
{ name: "Yogesh Sangwan Sir" },
{ name: "Abhinay Saxena Sir" },
{ name: "IT Training Room" },
{ name: "Ravi Bhasin Sir" },
{ name: "Audit Room & Legal Cell" },
{ name: "Deepika Bhaskar Mam" },
{ name: "Registrar Office" },
{ name: "Pallavi Kaushik Mam" },
{ name: "Deepali Gupta Mam" },
{ name: "B207" },
{ name: "B208" },
{ name: "B001" },
{ name: "B002" },
{ name: "B003" },
{ name: "Design & Innovation Lab" },
{ name: "B101" },
{ name: "Faculty Lounge" },
{ name: "B105" },
{ name: "Venkata Ratnadeep Suri Sir" },
{ name: "J.V Meenakshi Mam" },
{ name: "Gaurav Arora Sir" },
{ name: "Manohar Kumar Sir" },
{ name: "Kiriti Kanjilal Mam" },
{ name: "Paro Mishra Mam" },
{ name: "Sonia Baloni Ray Mam" },
{ name: "Smriti Singh Mam" },
{ name: "Gayatri Nair Mam" },
{ name: "Urban Research Lab" },
{ name: "Computational Social Sciences Lab" },
{ name: "Cognitive Science Lab" },
{ name: "Game Theory & Market Design Lab" },
{ name: "Kaushik Kalyanaraman Sir" },
{ name: "Sarthok Sircar Sir" },
{ name: "Monika Arora Mam" },
{ name: "Prahllad Deb Sir" },
{ name: "Sankha S Basu Sir" },
{ name: "Ashish Kumar Pandey Sir" },
{ name: "Sneha Chaubey Mam" },
{ name: "Subhashree Mohapatra Mam" },
{ name: "Debika Banerjee Mam" },
{ name: "Anuradha Sharma Mam" },
{ name: "Nabanita Ray Mam" },
{ name: "Maryam Mirzakhani Research Lab" },
{ name: "Paul Erdos Research Lab" },
{ name: "Math Innovation Lab" },
{ name: "M.Tech Lab 2" },
{ name: "M.Tech Lab 1" },
{ name: "Aayushi Shishodia Mam" },
{ name: "Bapi Chatterjee Sir" },
{ name: "Ranjitha Prasad Mam" },
{ name: "Raghava Mutharaju Sir" },
{ name: "Md.Shad Akhtar Sir" },
{ name: "Vinayak Abrol Sir" },
{ name: "Saket Anand Sir" },
{ name: "Sanjit Kaul Sir" },
{ name: "Shamik Sarkar Sir" },
{ name: "NAS Lab" },
{ name: "Vision Lab" },
{ name: "Flame" },
{ name: "Nice Lab" },
{ name: "Kracr Lab" },
{ name: "Cross-Caps Lab" },
{ name: "Distributed Computing & Learning Lab" },
{ name: "Iras Hub" },
{ name: "Diptapriyo Majumdar Mam" },
{ name: "Rinku Shah Sir" },
{ name: "Sambuddho Sir" },
{ name: "Arun Balaji Buduru Sir" },
{ name: "Syamantak Das Sir" },
{ name: "Vivek Kumar Sir" },
{ name: "Rajiv Raman Sir" },
{ name: "Debajyoti Bera Mam" },
{ name: "Mukulika Maity Mam" },
{ name: "Arani Bhattacharya Sir" },
{ name: "Nikhil Gupta Sir" },
{ name: "Supratim Shit Sir" },
{ name: "Theoretical Computer Science Lab" },
{ name: "Systems & Networks Lab" },
{ name: "Usable Security Group" },
{ name: "Cryptography Lab" },
{ name: "Ram Krishna Ghosh Sir" },
{ name: "Sanat K Biswas Sir" },
{ name: "Sayak Bhattacharya Sir" },
{ name: "A V Subramanyam Sir" },
{ name: "Sumit J Darak Sir" },
{ name: "Shobha Sundar Ram Sir" },
{ name: "Pragya Kosta Mam" },
{ name: "Sneh Saurabh Sir" },
{ name: "Anubha Gupta Mam" },
{ name: "Prasad Vilas Chanekar Sir" },
{ name: "SBI Lab" },
{ name: "Algorithms to Architecture Lab" },
{ name: "Space Systems Lab" },
{ name: "Automatic Control Lab" },
{ name: "C01" },
{ name: "C02" },
{ name: "C03" },
{ name: "C11" },
{ name: "C12" },
{ name: "C13" },
{ name: "C21" },
{ name: "C22" },
{ name: "C23" },
{ name: "C24" },
{ name: "Center For Technology & Policing" },
{ name: "Finance Executive" },
{ name: "Chetan Aggarwal Sir" },
{ name: "Finance & Account Dept" },
{ name: "Store & Purchase Dept" },
{ name: "Health Center" },
{ name: "HR Dept" },
{ name: "Student Affairs Dept" },
{ name: "Project & Operation Dept" },
{ name: "Chief Operating Officer" },
{ name: "Imran Yusuf Sir" },
{ name: "IT Dept" },
{ name: "Placement & IOP Office" },
{ name: "Registrar Office" },
{ name: "Academic Dept" },
{ name: "Comm & Alumni Dept" },
{ name: "Rubina Thakur Mam" },
{ name: "Sanjay Roy Sir" }

];

// Make sure the output folder exists
const outputDir = './qr-codes';
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir);
}

// Change this to your actual deployed URL
const baseUrl = 'https://last5sec.github.io/campus-navigation/index.html?place=';

infoData.forEach(item => {
  const url = baseUrl + encodeURIComponent(item.name);
  const fileName = `${outputDir}/${item.name.replace(/[\/\\?%*:|"<>]/g, '_')}.png`;
  QRCode.toFile(fileName, url, err => {
    if (err) console.error(`Error for ${item.name}:`, err);
    else console.log(`QR code generated for ${item.name}`);
  });
});